-- What a piece of music IS, as a person declared it or the engine witnessed it
-- (MUS-022): the director's own, generated by a provider, licensed, public
-- domain, or unknown — and `derived` for the row a derivative writes for
-- itself (a bounce, a separated stem, a take made over a source), whose
-- status is computed from its sources rather than declared. The default is
-- `unknown`, so no existing record gains an origin nobody stated.
ALTER TABLE film_rights ADD COLUMN origin TEXT NOT NULL DEFAULT 'unknown'
    CHECK (origin IN ('original', 'generated', 'licensed', 'public_domain', 'unknown', 'derived'));
