/**
 * A project's provider choices, read once.
 *
 * This existed SEVEN times — byte-identical copies of the same four lines in
 * lipsync.js, video-gen.js, music-gen.js, post-production.js, locations.js,
 * characters.js and voice.js. Seven copies of a function is a standing invitation
 * for six of them to stay behind when the seventh learns something, and that is
 * exactly what happened here: every copy is handed a `projectId`, uses it to read
 * one column, and throws it away — one line before `resolve()` needed it to
 * attribute what the call was about to spend.
 *
 * So the config object carries its own project id. `resolve()` reads it and the
 * meter attributes the spend, and not one of the thirty-one call sites had to
 * change shape to make that work.
 *
 * The id is NON-ENUMERABLE on purpose. This object is compared, spread and
 * occasionally serialised as the project's provider settings; a visible extra
 * key would show up in the Provider Settings panel as a capability nobody can
 * configure, and would round-trip into film_projects.provider_config on the
 * next save.
 */

/**
 * Attach attribution to a parsed config without making it a visible key.
 *
 * Non-enumerable throughout: this object is spread, compared and occasionally
 * serialised back into film_projects.provider_config, and a visible extra key
 * would surface in the Provider Settings panel as a capability nobody can
 * configure.
 */
function tag(config, projectId, shotId, sceneId) {
    const out = config || {};
    const hide = (key, value) => {
        if (value === undefined || value === null) return;
        Object.defineProperty(out, key, { value, enumerable: false, writable: true, configurable: true });
    };
    hide('__project_id', projectId);
    hide('__shot_id', shotId);
    hide('__scene_id', sceneId);
    return out;
}

/**
 * The provider config for a generation, carrying WHICH SHOT it is for.
 *
 * The config object is the one thing that already travels from a route into
 * resolve(), so it is what attribution rides on. The alternative — tagging the
 * payload — does not survive: callImageGen rebuilds its request body with a
 * spread, and a spread drops non-enumerable properties silently. Every frame
 * generated through the board was attributed to the project and to no shot,
 * and the per-shot table populated only from a backfill, which reads shot ids
 * off the assets instead.
 *
 * @param {object} project - a film_projects row (or at minimum `{ id }`)
 * @param {object} [shot]  - a film_shots row; its scene_id is used when present
 * @param {object} [scene] - a film_scenes row, when there is no shot
 */
function spendContext(project, shot, scene, overrides) {
    const projectId = project && (project.id || project.project_id);
    let config = projectId ? providerConfigFor(projectId) : {};
    /*
     * A choice made for THIS generation only.
     *
     * The quality tier is a project setting, which is right for the default and
     * wrong for the moment a director is looking at one frame that came back
     * badly and wants to spend more on it — or is trying three compositions and
     * wants to spend less. Overriding the config for one call keeps that a
     * decision about this frame rather than a setting they have to remember to
     * put back, which is how a project ends up shooting a whole board on the
     * expensive tier because of one difficult shot.
     */
    if (overrides && (overrides.image_quality || overrides.image_model || overrides.image)) {
        config = tag({ ...config,
            ...(overrides.image ? { image: overrides.image } : {}),
            ...(overrides.image_quality ? { image_quality: overrides.image_quality } : {}),
            ...(overrides.image_model ? { image_model: overrides.image_model } : {}),
        }, projectId);
    }
    // Shot rows reach this two ways. A `SELECT * FROM film_shots` row has
    // `id`; the storyboard's shotlist query aliases it to `shot_id` and joins
    // the scene alongside. Reading only `id` silently attributes every frame
    // generated by "Generate All" to no shot — which looks exactly like a
    // project nobody generated, and is the failure this context exists to fix.
    return tag(config, projectId,
        shot && (shot.id || shot.shot_id),
        (scene && (scene.id || scene.scene_id)) || (shot && shot.scene_id));
}

/** Provider config for a project id, tagged for cost attribution. */
function providerConfigFor(projectId) {
    if (!projectId) return {};
    const { db } = require('../db/database');
    const row = db.prepare('SELECT provider_config FROM film_projects WHERE id = ?').get(projectId);
    if (!row) return tag({}, projectId);
    try { return tag(JSON.parse(row.provider_config || '{}'), projectId); }
    catch (_) { return tag({}, projectId); }
}

/** Same, from a project ROW that was already loaded — no second query. */
function providerConfigOf(project) {
    if (!project) return {};
    try { return tag(JSON.parse(project.provider_config || '{}'), project.id); }
    catch (_) { return tag({}, project.id); }
}

module.exports = { providerConfigFor, providerConfigOf, spendContext, tag };
